name: Unit Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^16
      - name: Install flow cli
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
      - name: Start flow emulator
        run: nohup flow emulator &
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --runInBand

  tests-overflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: run tests
        run: go test -timeout 30m -json ./... > test.json
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.0
        with:
          test-results: test.json